### ISSUE TITLE
Technologienamen vergleichen

### ISSUE THREAD

**Issue by r-dannhauer** [r-dannhauer/GermanProductionLineTranslation#15]

**Comment by Fox2k11** [comment]
Oh ein bug? was meinst du mit Technologienamen Vergleichen?

**Comment by r-dannhauer** [comment]
Ja, "bug" XD
Die Technologien heißen in verschiedenen Dateien anders.

**Comment by Fox2k11** [comment]
ja hab schon auf Steam kommentiert woran das Liegt.. hast du den scho nwas genaues oder ist das ein größerer Bug?

**Comment by r-dannhauer** [comment]
Ich denke nicht, dass das groß sein wird. Ich setze mich da ma am Wochenende dran.

**Comment by Fox2k11** [comment]
Okay.. ansonsten hätte man das schnell ausgebessert wenn das nur kleinere sachen sind aber besser wenn man es nochmal ghenau macht =)
