### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by r-dannhauer** [r-dannhauer/GermanProductionLineTranslation#9]

**Comment by Payspro** [comment]
Ich arbeite zur Zeit an der Übersetzung des Tutorial.

**Comment by Fox2k11** [comment]
okay dann werd ich mir mal die achievments zur brust nehmen ;)

**Comment by Fox2k11** [comment]
Robert ist Payspro noch am Tutorial drann? ne rückmeldung von Ihm wäre nicht schlecht!

**Comment by r-dannhauer** [comment]
Ich weiß es nicht. Ich kann auch nur das lesen, was hier kommuniziert wurde.

**Comment by Payspro** [comment]
Hey, zur Zeit komme ich leider nicht dazu weiter dran zu arbeiten. Ich habe es aber nicht vergessen. Ihr dürft natürlich auch gerne meine 40% nehmen und darauf aufbauen :D

**Comment by Fox2k11** [comment]
OKay.. danke für die rückmeldung =)
